export {default as Challenge } from "./About the Challenge.png"
export {default as Eligibility} from "./Eligibility.png"
export {default as Ellipse0} from "./Ellipse 10.png"
export {default as Ellipse1} from "./Ellipse 11.png"
export {default as Ellipse2} from "./Ellipse 12.png"
export {default as Ellipse3} from "./Ellipse 13.png"
export {default as Ellipse4} from "./Ellipse 14.png"
export {default as Ellipse5} from "./Ellipse 15.png"
export {default as Ellipse7} from "./Ellipse 17.png"
export {default as Ellipse8} from "./Ellipse 18.png"
export {default as Ellipse9} from "./Ellipse 19.png"
export {default as Ellipse10} from "./Ellipse 20.png"
export {default as Ellipse11} from "./Ellipse 21.png"
export {default as Ellipse12} from "./Ellipse 22.png"
export {default as Ellipse13} from "./Ellipse 13.png"
export {default as Group2} from "./Group 2.png"
export {default as Group3} from "./Group 3.png"
export {default as Group4} from "./Group 4.png"
export {default as Group6} from "./Group 6.png"
export {default as Group7} from "./Group 7.png"
export {default as Challenge2} from "./How the Challenge Works.png"